更新ci配置

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,5 @@
-#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
 defaults: &defaults
+  #working_directory: ./circleci
   docker:
     - image: circleci/node:8
 
@@ -9,14 +9,15 @@ jobs:
     <<: *defaults
     steps:
       - checkout
+      # Download and cache dependencies
       - restore_cache:
           keys:
-            - v2-dependencies-{{ checksum "package.json" }}
-      - run: yarn install
+            - v1-dependencies-{{ checksum "package.json" }}
+      - run: npm install
       - save_cache:
           paths:
             - node_modules
-          key: v2-dependencies-{{ checksum "package.json" }}
+          key: v1-dependencies-{{ checksum "package.json" }}
       - persist_to_workspace:
           root: .
           paths:
@@ -27,29 +28,101 @@ jobs:
       - checkout
       - attach_workspace:
           at: .
-      - run: yarn build
+      - run: npm run build
       - persist_to_workspace:
           root: .
           paths:
-            - dist
-  test:
+            - build
+  tu:
     <<: *defaults
     steps:
       - checkout
       - attach_workspace:
           at: .
-      - run: yarn ci
-      - store_test_results:
-          path: test-results
-
+      - run: npm run test
+  e2e:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run: npm run test
+  lint:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run: npm run lint
+  deploy-github:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - deploy:
+          name: Deploy to GitHub Pages
+          command: |
+            set -e
+            remote=$(git config remote.origin.url)
+            if [ ! -d "build" ]
+            then
+                echo "build folder not found"
+                exit 1
+            fi
+            mkdir gh-pages-branch
+            cd gh-pages-branch
+            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
+            git config --global user.name "$GH_NAME" > /dev/null 2>&1
+            git init
+            git remote add --fetch origin "$remote"
+            if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
+            then
+                git checkout gh-pages
+                git rm -rf .
+            else
+                git checkout --orphan gh-pages
+            fi
+            cp -a "../build/." .
+            git add -A
+            git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
+            git push --force --quiet origin gh-pages > /dev/null 2>&1
+            cd ..
+            rm -rf gh-pages-branch
+            echo "Finished GitHub pages Deployment!"
+  deploy-prod:
+    <<: *defaults
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - deploy:
+          name: Deploy to Production
+          command: |
+            echo "iooooooo"
 workflows:
   version: 2
   build_accept_deploy:
     jobs:
       - prepare
-      - build:
-          requires:
-            - test
-      - test:
+      - lint:
           requires:
             - prepare
+      - build:
+          requires:
+            - lint
+      - tu:
+          requires:
+            - build
+      - e2e:
+          requires:
+            - build
+      - deploy-github:
+          requires:
+            - tu
+            - e2e
+      - deploy-prod:
+          type: approval
+          requires:
+            - tu
+            - e2e
